const trashBins = [
  { id: 177, district: "종로구", address: "세종로 23-3", place: "의정부지 역사공원 앞", category: "광장, 공원", type: "일반쓰레기" },
  { id: 178, district: "종로구", address: "세종로 23-3", place: "의정부지 역사공원 앞", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 289, district: "종로구", address: "송현동 60-8", place: "열린송현공원 동측 입구", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 290, district: "종로구", address: "송현동 60-8", place: "열린송현공원 동측 입구", category: "광장, 공원", type: "일반쓰레기" },
  { id: 291, district: "종로구", address: "송현동 48-9", place: "열린송현공원 서측 입구", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 292, district: "종로구", address: "송현동 48-9", place: "열린송현공원 서측 입구", category: "광장, 공원", type: "일반쓰레기" },
  { id: 293, district: "종로구", address: "대학로 104", place: "마로니에 공원 입구", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 294, district: "종로구", address: "대학로 104", place: "마로니에 공원 입구", category: "광장, 공원", type: "일반쓰레기" },
  { id: 843, district: "용산구", address: "문배동 24-39", place: "아크로타워", category: "광장, 공원", type: "담배꽁초 수거함" },
  { id: 1454, district: "성북구", address: "동소문동2가 2-4", place: "성북천 분수광장 평화의소녀상 앞", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 1540, district: "성북구", address: "석관동 375-29", place: "우리은행 앞 광장", category: "광장, 공원", type: "일반쓰레기" },
  { id: 1598, district: "성북구", address: "삼선동5가 411", place: "성북구청 바람마당", category: "광장, 공원", type: "일반쓰레기" },
  { id: 1601, district: "성북구", address: "종암동 65-13", place: "문화공간 이육사 앞 공원", category: "광장, 공원", type: "일반쓰레기" },
  { id: 1603, district: "성북구", address: "석관동 375-29", place: "우리은행 앞 광장", category: "광장, 공원", type: "일반쓰레기" },
  { id: 1620, district: "성북구", address: "삼선동5가 411", place: "성북구청 바람마당", category: "광장, 공원", type: "일반쓰레기" },
  { id: 1621, district: "성북구", address: "삼선동5가 411", place: "성북구청 바람마당", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 1647, district: "성북구", address: "하월곡동 22-13", place: "진각종 앞 달빛공원", category: "광장, 공원", type: "일반쓰레기" },
  { id: 1648, district: "성북구", address: "하월곡동 22-13", place: "진각종 앞 달빛공원", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 1663, district: "성북구", address: "동소문로20다길 30-9", place: "-", category: "광장, 공원", type: "담배꽁초 수거함" },
  { id: 1672, district: "성북구", address: "아리랑로54", place: "-", category: "광장, 공원", type: "담배꽁초 수거함" },
  { id: 1673, district: "성북구", address: "보국문로9-3", place: "-", category: "광장, 공원", type: "담배꽁초 수거함" },
  { id: 1674, district: "성북구", address: "보국문로19", place: "-", category: "광장, 공원", type: "담배꽁초 수거함" },
  { id: 1961, district: "도봉구", address: "우이천로 308", place: "한일병원 정문 앞", category: "광장, 공원", type: "일반쓰레기" },
  { id: 2021, district: "도봉구", address: "마들로 916", place: "도봉산역2번출구(창포원 입구 앞)", category: "광장, 공원", type: "일반쓰레기" },
  { id: 2138, district: "도봉구", address: "덕릉로 398", place: "주공17단지 상가 앞", category: "광장, 공원", type: "일반쓰레기" },
  { id: 2471, district: "은평구", address: "연서로 10", place: "연서로 10 응암 소공원(리드힐병원 맞은편)", category: "광장, 공원", type: "일반쓰레기" },
  { id: 2472, district: "은평구", address: "연서로 10", place: "연서로 10 응암 소공원(리드힐병원 맞은편)", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 3273, district: "마포구", address: "노고산동31-123", place: "신촌역 6번출구 공원안쪽", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3274, district: "마포구", address: "노고산동31-123", place: "신촌역 6번출구 공원안쪽", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3278, district: "마포구", address: "독막로221", place: "독막로221 정자나무 공원안", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3282, district: "마포구", address: "창전로32", place: "창전로32 서강나루공원앞", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3406, district: "마포구", address: "월드컵로212", place: "구청 광장 대로변", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3476, district: "마포구", address: "고산2길61", place: "고산2길 61 노고산체육공원", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3477, district: "마포구", address: "월드컵로212", place: "구청 광장", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3478, district: "마포구", address: "월드컵로212", place: "구청 광장 재활용", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 3479, district: "마포구", address: "어울마당로 76", place: "빈티지플러스 홍대점 앞", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3481, district: "마포구", address: "어울마당로 65", place: "홍대상상마당 부근", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3482, district: "마포구", address: "어울마당로 65", place: "홍대상상마당 부근", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3572, district: "양천구", address: "목동서로159-2", place: "오목공원(CBS교차로 앞 횡단보도)", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3573, district: "양천구", address: "목동서로159-2", place: "오목공원(CBS교차로 앞 횡단보도)", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 3586, district: "양천구", address: "목동서로77", place: "파리공원 사잇길(민원으로 회수)", category: "광장, 공원", type: "일반쓰레기" },
  { id: 3587, district: "양천구", address: "목동서로77", place: "파리공원 사잇길(민원으로 회수)", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 4085, district: "구로구", address: "경인로 673-1", place: "공원 앞", category: "광장, 공원", type: "일반쓰레기" },
  { id: 4237, district: "구로구", address: "오류로 86", place: "오류소공원 내", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 4238, district: "구로구", address: "오류로 86", place: "오류소공원 내", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 4403, district: "영등포구", address: "여의나루로 50", place: "교직원공제회 앞, 흡연부스 방향", category: "광장, 공원", type: "일반쓰레기" },
  { id: 4404, district: "영등포구", address: "여의나루로 50", place: "교직원공제회 앞, 흡연부스 방향", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 4405, district: "영등포구", address: "여의나루로 50", place: "교직원공제회 앞, 흡연부스 방향", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 4406, district: "영등포구", address: "양평동4가 301-7", place: "양평동 어린이공원", category: "광장, 공원", type: "일반쓰레기" },
  { id: 4407, district: "영등포구", address: "양평동4가 301-7", place: "양평동 어린이공원", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 4408, district: "영등포구", address: "도림로47길28", place: "원지어린이공원", category: "광장, 공원", type: "일반쓰레기" },
  { id: 5160, district: "관악구", address: "난우10가길 40", place: "주차장", category: "광장, 공원", type: "담배꽁초 수거함" },
  { id: 5184, district: "관악구", address: "봉림교가로녹지", place: "", category: "광장, 공원", type: "담배꽁초 수거함" },
  { id: 5216, district: "관악구", address: "남부순환로 1583", place: "공원", category: "광장, 공원", type: "담배꽁초 수거함" },
  { id: 6458, district: "강남구", address: "밤고개로99", place: "수서SRT역 입구", category: "광장, 공원", type: "일반쓰레기" },
  { id: 6459, district: "강남구", address: "밤고개로99", place: "수서SRT역 입구", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 6498, district: "강남구", address: "자곡로3길21", place: "LH강남힐스테이트505동옆", category: "광장, 공원", type: "일반쓰레기" },
  { id: 6499, district: "강남구", address: "자곡로3길21", place: "LH강남힐스테이트505동옆", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 6590, district: "송파구", address: "마천로 392", place: "남한산성 만남의장소 옆", category: "광장, 공원", type: "일반쓰레기" },
  { id: 6591, district: "송파구", address: "마천로 392", place: "남한산성 만남의장소 옆", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 6634, district: "송파구", address: "장지동 896-1(위례중앙로)", place: "위례중앙광장(장지동 896-1)", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 6635, district: "송파구", address: "장지동 896-1(위례중앙로)", place: "위례중앙광장(장지동 896-1)", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 6636, district: "송파구", address: "장지동 896-1(위례중앙로)", place: "위례중앙광장(장지동 896-1)", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 6637, district: "송파구", address: "장지동 896-1(위례중앙로)", place: "위례중앙광장(장지동 896-1)", category: "광장, 공원", type: "재활용쓰레기" },
  { id: 6638, district: "송파구", address: "장지동 896-1(위례중앙로)", place: "위례중앙광장(장지동 896-1)", category: "광장, 공원", type: "일반쓰레기" }
];
